
import EditBudgetForm from '@/components/Budget/EditBudgetForm'
import { getBudget } from '@/src/services'
import { Metadata } from 'next'
import { Params } from 'next/dist/shared/lib/router/utils/route-matcher'
import Link from 'next/link'





export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
    const { id } = params
    const budget = await getBudget({id})
    return {
        title: `Cashtrackr - ${budget[0].name}`,
        description: "Generated by create next app",
    }
}

export default async function page({ params }: { params: Params }) {
    const { id } = params
    const data = await getBudget({ id })

    return (
        <>
            <div className='flex flex-col-reverse md:flex-row md:justify-between items-center'>
                <div className='w-full md:w-auto'>
                    <h1 className='font-black text-4xl text-purple-950 my-5'>
                        Editar Presupuesto:{data[0].name}
                    </h1>
                    <p className="text-xl font-bold">Llena el formulario y crea un nuevo {''}
                        <span className="text-amber-500">presupuesto</span>
                    </p>
                </div>
                <Link
                    href={'/admin'}
                    className='bg-amber-500 p-2 rounded-lg text-white font-bold w-full md:w-auto text-center'
                >
                    Volver
                </Link>
            </div>
            <div className='p-10 mt-10  shadow-lg border '>
                <EditBudgetForm data={data[0]} />
            </div>
        </>
    )
}
